pr:
  autoCancel: true

jobs:

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      htslib115:
        htslib_version: '1.15'
      htslib116:
        htslib_version: '1.16'
      htslib117:
        htslib_version: '1.17'
    maxParallel: 1

  steps:
  - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    displayName: Add conda to PATH
  - bash: conda create -n MethylDackel -q --yes -c conda-forge -c bioconda htslib=$(HTSLIB_VERSION) python gcc_impl_linux-64 binutils_impl_linux-64 binutils_linux-64 gcc_linux-64 libgcc-ng libbigwig
    displayName: Installing dependencies
  - template: .azure-pipelines/test-template.yml

#This tries to link against 32-bit libraries for some reason
- job: 'OSX'
  pool:
    vmImage: 'macOS-latest'
  strategy:
    matrix:
      htslib111:
        htslib_version: '1.11'
      htslib112:
        htslib_version: '1.12'
      htslib113:
        htslib_version: '1.13'
      htslib114:
        htslib_version: '1.14'
    maxParallel: 1

  steps:
  - script: |
      echo "Removing homebrew from Azure to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew
    displayName: Remove homebrew
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  - bash: sudo chown -R 501:20 /usr/local/miniconda/pkgs
    displayName: Fix permissions
  - bash: conda create -n MethylDackel -q --yes -c conda-forge -c bioconda htslib=$(HTSLIB_VERSION) python clang=11.1.0 clang-11 clang_osx-64=11.1.0 clangxx=11.1.0 cctools_osx-64 compiler-rt ld64_osx-64 libcxx make libbigwig
    displayName: Installing dependencies
  - template: .azure-pipelines/test-template.yml
