steps:
- bash: |
    source activate MethylDackel
    export CONDA_BUILD_SYSROOT=''
    make install CC=$CC CFLAGS="-O3 -Wall -I$CONDA_PREFIX/include" LIBS="-L$CONDA_PREFIX/lib" LIBBIGWIG="$CONDA_PREFIX/lib/libBigWig.a" prefix=$CONDA_PREFIX/bin
  displayName: Installing methylDackel
- bash: |
    source activate MethylDackel
    export LD_LIBRARY_PATH=$CONDA_PREFIX/lib
    export LC_RPATH=$LD_LIBRARY_PATH
    #ls -l
    install_name_tool -add_rpath @$CONDA_PREFIX/lib MethylDackel
    #otool -L MethylDackel
    #otool -L $CONDA_PREFIX/lib/libhts.1.11.dylib
    ./MethylDackel --version
    #DYLD_PRINT_LIBRARIES=1 ./MethylDackel extract tests/ct100.fa tests/ct_aln.bam -q 2 -o test1
    python tests/test.py
  displayName: Test methylDackel
